### ISSUE TITLE
Site hacked?

### ISSUE THREAD

**Issue by terryf82** [getapid/apid#197]
https://getapid.com currently returning a deceptive site warning from both FireFox and Chrome, looks to have been taken over by a phishing site:

<img width="1363" alt="Screen Shot 2022-03-25 at 4 02 50 pm" src="https://user-images.githubusercontent.com/8789832/160063825-7e819cc8-147d-4d3f-bb10-385092ca634d.png">

**Comment by iv-p** [comment]
Hi! The site is not hacked, I thought I removed all references to the domain since I didn't renew it. It was a bit pointless since all the information is now in github including docs and FAQ :)

Thanks for raising this!
